services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://dietpi.tailb781d6.ts.net"
    volumes:
      - ./vw-data/:/data/
    ports:
      - "8080:80"

