---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Bookmarks:
   - Github:
      - abbr: GH
        icon: github-light.png
        href: https://github.com/
   - DeepSeek:
      - icon: deepseek.png
        href: https://chat.deepseek.com/
   - ChatGPT:
      - icon: chatgpt.png
        href: https://chatgpt.com/   
   - Gemini: 
      - icon: google-gemini.png
        href: https://gemini.google.com/
   - Claude:
      - icon: claude-ai.png
        href: https://claude.ai/
   - Reddit:
      - abbr: RE
        icon: reddit.png
        href: https://reddit.com/
   - YouTube:
      - abbr: YT
        icon: youtube.png
        href: https://youtube.com/
